In [1]:
import torch

In [2]:
# 0 D tensor
x = torch.tensor(5)
print(x.ndim)

# matrix 
m = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
print("matrix tensor Dimension:",m.ndim)
print("shape of tensor:",m.shape)
print(m)
print(m.dtype)

0
matrix tensor Dimension: 2
shape of tensor: torch.Size([2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32


###  Special Tensor Creation

In [3]:
ones = torch.ones(2,3,dtype=torch.int64)
print("ones:\n",ones)
# zeros 
zeros = torch.zeros(2,2)
print("zeros:\n",zeros)
# random numbers
randd = torch.rand(3,3)
print("randoms:\n",randd)
# range tensor
y = torch.arange(1,10)
print("range:",y)
# reshape
print("reshape:\n",y.reshape(3,3))
# indexing
z = torch.tensor([
    [10, 20, 30],
    [40, 50, 60]
])
print(z[0])
print(z[1][1])
# slicing
x = torch.tensor([1, 2, 3, 4, 5])

print(x[1:4])
print(x[0:3])


ones:
 tensor([[1, 1, 1],
        [1, 1, 1]])
zeros:
 tensor([[0., 0.],
        [0., 0.]])
randoms:
 tensor([[0.9832, 0.8405, 0.3504],
        [0.0955, 0.6263, 0.2498],
        [0.2529, 0.1023, 0.0563]])
range: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshape:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([10, 20, 30])
tensor(50)
tensor([2, 3, 4])
tensor([1, 2, 3])


In [6]:
# Arthimatic operations
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print("addition:\n",x+y)
print("subtraction:\n",x-y)
print("multiplication:\n",x*y)
print("division:\n",x*y)
print("power:\n",x**2)

meann = torch.tensor([1, 2, 3, 4], dtype=torch.float32)
print("mean:\n",torch.mean(meann))
s = torch.tensor([1, 2, 3, 4])

print("sum:\n",torch.sum(s))
# maximum value
maax = torch.tensor([5, 2, 9, 1])

print("max:\n",torch.max(maax))
minn = torch.tensor([5, 2, 9, 1])

print("min:\n",torch.min(minn))
# armax
x = torch.tensor([5, 2, 9, 1])

print("argmax:\n",torch.argmax(x))
x = torch.tensor([5, 2, 9, 1])

print("argmin:\n",torch.argmin(x))

addition:
 tensor([5, 7, 9])
subtraction:
 tensor([-3, -3, -3])
multiplication:
 tensor([ 4, 10, 18])
division:
 tensor([ 4, 10, 18])
power:
 tensor([1, 4, 9])
mean:
 tensor(2.5000)
sum:
 tensor(10)
max:
 tensor(9)
min:
 tensor(1)
argmax:
 tensor(2)
argmin:
 tensor(3)
