In [7]:
# sturcture of custome dataset
from torch.utils.data import Dataset
class MyDataset(Dataset):
    def __int__(self):
        pass
    def __len__(self):
        pass
        
    def __getitem__(self, key):
        pass
    
      
    
 
    

In [8]:
# first pracitcal example
from torch.utils.data import Dataset
class DatasetNumber(Dataset):
    def __init__(self):
        self.data = [1,2,3,4,5,6]
    def __len__(self):
        return len(self.data)
    def __getitem__(self, index):
        return self.data[index]
       
        
        
dataset = DatasetNumber()

print(len(dataset))
print(dataset[0])
print(dataset[2])

6
1
3


## DataLoader


In [9]:
from torch.utils.data import DataLoader
dataset = DatasetNumber()
loader = DataLoader(dataset,batch_size=2)
for batch in loader:
    print(batch)



tensor([1, 2])
tensor([3, 4])
tensor([5, 6])


## Custom Dataset for Features and Labels

In [10]:
from torch.utils.data import DataLoader ,dataset
import torch
class StudentClass(Dataset):
    def __init__(self):
        self.x = torch.tensor([
            [1.0,2.0],
            [3.0,4.0],
            [5.0,6.0]
        ])
        self.y = torch.tensor([1,0,1,0])
    def __len__(self):
        return len(self.x)
    def __getitem__(self, index):
        return self.x[index],self.y[index]
dataset = StudentClass()

loader = DataLoader(dataset,
                    batch_size=2,
                    shuffle=True)

In [11]:
for features, labels in loader:

    print("Features:")
    print(features)

    print("Labels:")
    print(labels)

Features:
tensor([[3., 4.],
        [1., 2.]])
Labels:
tensor([0, 1])
Features:
tensor([[5., 6.]])
Labels:
tensor([1])


In [ ]:
# CSV FILE READ
import pandas as pd
import torch
from torch.utils.data import Dataset

class CSVDataset(Dataset):

    def __init__(self, file_name):

        data = pd.read_csv(file_name)

        self.x = torch.tensor(
            data.iloc[:, :-1].values,
            dtype=torch.float32
        )

        self.y = torch.tensor(
            data.iloc[:, -1].values,
            dtype=torch.long
        )

    def __len__(self):
        return len(self.x)

    def __getitem__(self, index):
        return self.x[index], self.y[index]